import os
import subprocess

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models.tunnel import Tunnel


class HAProxyService:
    """
    Generates HAProxy config snippets to be included in the existing
    HAProxy configuration on homeaccess.site.

    Two files are generated:
    - homevpn-backends.cfg: backend blocks for each active tunnel
    - homevpn-subdomains.map: subdomain-to-backend map file

    The existing HAProxy config should include:
        # In the frontend section:
        http-request set-var(req.subdomain) req.hdr(host),lower,regsub(\.domoteus\.com$,,)
        use_backend %[var(req.subdomain),map(/etc/haproxy/homevpn-subdomains.map)]

        # At the end:
        .include /etc/haproxy/homevpn-backends.cfg
    """

    def __init__(self):
        self.backends_path = settings.haproxy_backends_path
        self.map_path = settings.haproxy_map_path

    async def regenerate_config(self, db: AsyncSession) -> None:
        result = await db.execute(
            select(Tunnel).where(Tunnel.is_active == True)  # noqa: E712
        )
        tunnels = result.scalars().all()

        backends_lines = [
            "# Auto-generated by HomeVPN API. Do not edit manually.\n"
        ]
        map_entries = []

        for tunnel in tunnels:
            backend_name = f"bk_hvpn_{tunnel.subdomain}"
            backends_lines.append(f"backend {backend_name}")
            target_ip = tunnel.device_ip if tunnel.use_device_ip else tunnel.vpn_ip
            backends_lines.append(
                f"    server srv1 {target_ip}:{tunnel.target_port} check inter 10s fall 3 rise 2"
            )
            backends_lines.append("")
            map_entries.append(f"{tunnel.subdomain} {backend_name}")

        # Write backends config file
        os.makedirs(os.path.dirname(self.backends_path), exist_ok=True)
        with open(self.backends_path, "w") as f:
            f.write("\n".join(backends_lines))

        # Write map file
        os.makedirs(os.path.dirname(self.map_path), exist_ok=True)
        with open(self.map_path, "w") as f:
            f.write("# Auto-generated by HomeVPN API. Do not edit manually.\n")
            if map_entries:
                f.write("\n".join(map_entries) + "\n")

        self._reload()

    def _reload(self) -> None:
        """Reload HAProxy via sudo systemctl (allowed via sudoers.d/homevpn)."""
        try:
            subprocess.run(
                ["sudo", "systemctl", "reload", "haproxy"],
                check=True,
                capture_output=True,
            )
        except (subprocess.CalledProcessError, FileNotFoundError):
            pass


haproxy_service = HAProxyService()
